/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  export type SvgName = string;
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<SvgName>;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<SvgName>;
          default: string;
          required: true;
      };
  }>>, {
      name: SvgName;
  }>;
  export const svgNames: SvgName[];
  export default SvgIcon;
}
